### ISSUE TITLE
"and" logic does not work on mulitiple checkboxes

### ISSUE THREAD

**Issue by juergenweb** [bomsn/mf-conditional-fields#12]
First of all, thank you for this wonderful script!

I have discovered a problem by using multiple checkboxes and using the "and" logic. Here is the description of the problem. It could also be, that I did something wrong, but I am not able to figure it out. Just to mention: using the "or" logic works as expected.

### Description: 

I have 3 checkboxes with the values "1", "2" and "3" 

```html
<input id="contactform-multicheckboxhorizontalarray-0" name="contactform-multicheckboxhorizontalarray[]" type="checkbox" class="checkbox" value="1">
<input id="contactform-multicheckboxhorizontalarray-1" name="contactform-multicheckboxhorizontalarray[]" type="checkbox" class="checkbox" value="2">
<input id="contactform-multicheckboxhorizontalarray-2" name="contactform-multicheckboxhorizontalarray[]" type="checkbox" class="checkbox" value="3">
```

I want to hide another field if values "1" **and** "3" are selected. I use the inline-method with PHP and this is my condition:

```php
$condition = get_mf_conditional_rules( 'hide', array(
              array(
                'name' => 'contactform-multicheckboxhorizontalarray',
                'operator' => 'is',
                'value' => '1'
              ),
              array(
                'name' => 'contactform-multicheckboxhorizontalarray',
                'operator' => 'is',
                'value' => '3'
              ),
            ), 'and');
```

This is what my json string looks like:

```json
'{"container":".fieldwrapper","action":"hide","rules":[{"name":"contactform-multicheckboxhorizontalarray","operator":"is","value":"1"},{"name":"contactform-multicheckboxhorizontalarray","operator":"is","value":"3"}],"logic":"and"}'
```

But if I check "1" and "3" the dependend field is still visible, so nothing happens. So is this a bug or am I still missing something to get it work.

Thanks for your help! 

Jürgen

**Comment by juergenweb** [comment]
Ok, I found it out, how it works. Instead of using 2 rules I have to change the value:

```php
$condition = get_mf_conditional_rules( 'hide', array(
              array(
                'name' => 'contactform-multicheckboxhorizontalarray',
                'operator' => 'is',
                'value' => '1|3'
              )));
```
Using only one rule with the values separated by "|" works. If this is the way it should work, you can close this issue as solved.

**Comment by bomsn** [comment]
Hello @juergenweb , 
Good to hear you got it sorted :)

Yes, array values are converted to a string and separated with "|", this is how it's implemented inside the library.
```javascript
	// Convert array to a string in the last loop iteration
	if (i === trigger.length - 1) {
		triggerValue = triggerValue.join('|');
	}
```
