### ISSUE TITLE
Eventlistener does not recognize fields where the name ends with []

### ISSUE THREAD

**Issue by juergenweb** [bomsn/mf-conditional-fields#13]
I have discovered an issue using a select multiple inputfield.

Description: 
To send data of a select multiple inputfield via POST to the server, you will need to add "[]" at the end of the name attribute. This forces the sending of the form data to be an array for this inputfield.

`
<select name="myselect[]" multiple>
`

Problem: 
The problem is that the ending with [] leads to it that eventlistener ignore this inputfield and does not take care about changes.
If I remove "[]" than the eventlistener will be triggered, but the triggerValue is always a single value even if I select multiple values.

So the code must be changed to accept attribute names with [] too.

**Comment by bomsn** [comment]
Hey @juergenweb 

Can you provide a sample html file or code where we can replicate the issue?

**Comment by juergenweb** [comment]
Strange! Now it works!

I have tried it with ` 'name' => 'css[]'` and ` 'name' => 'css'` (css is the field name of the multiple select) without luck, but now it works as expected.

So I close this this issue. Sorry for the inconveniences.

**Comment by bomsn** [comment]
Perfect, good to hear you got it sorted.
