### ISSUE TITLE
Select multiple input field does not support condition with multiple values and AND operator

### ISSUE THREAD

**Issue by juergenweb** [bomsn/mf-conditional-fields#14]
**Description:** 

A select multiple field allows to select one or more values (like the checkbox multiple). Therefore an AND condition like 

`'name' => 'css[]',
            'operator' => 'is',
            'value' => 'CSS 2|CSS 3'`

should be supported too.

**Current situation**

At the moment, it only supports the checking of 1 certain value or the checking of more values with the OR logic, but it does not support the checking of more values with AND logic (eg. show field 2 only if value 1 **and** 3 will be selected on field 1).

Looking at the source code gives me the information that this feature is not implemented yet. It is only implemented for checkboxes and radios at line 324 and below.

I have also tested it by writing 2 conditions with adding the "and" operator afterwards, but this does not work too.

I have added an example code so you can try it out by yourself (I have attached it as an txt file instead of php, because Github does not allow adding files with ending php as an attachement. So please rename it to php after download to get it working)

Best regards Jürgen

[select-multiple-example.txt](https://github.com/user-attachments/files/16172089/select-multiple-example.txt)

**Comment by bomsn** [comment]
This has been fixed in the recent update. Thank you for reporting this.

**Comment by juergenweb** [comment]
Thank you for the fast fix - works like a charm :-)
