### ISSUE TITLE
Publish to npmjs registry

### ISSUE THREAD

**Issue by Martin1982** [bomsn/mf-conditional-fields#16]
The package looks very promising, but to use it in a project I now have to add the git repo to my package.json.  Is it possible to create a release that is published on npmjs to easily include it in a project?

**Comment by bomsn** [comment]
Hello, yes, sure, 
Will send an update here once sorted.

**Comment by bomsn** [comment]
I've added the npm version: https://www.npmjs.com/package/mf-conditional-fields

**Comment by Martin1982** [comment]
Awesome! Thank you for the quick response. Awarded it with another star here :)
