### ISSUE TITLE
[Improvements] Add disable action

### ISSUE THREAD

**Issue by Tropicalista** [bomsn/mf-conditional-fields#3]
At the moment the only action supported are hide and show. A nice addition would be a `disable` action.

This can be useful to disable certain field until a correct value is entered. And also the most used use case is to disable the button, for example if the privacy policy is not accepted.

I have digged a bit trough the code, but seems not a simple implementations at the moment. It would require some code refactoring.

**Comment by bomsn** [comment]
Feature is added, you can now simply pass the enable/disable action in the rules.
For example:

    // Parent Field
    <input type="checkbox" name="disable_parent" id="disable_parent" value="yes"> <label for="disable_parent">

 
    // Child field
    <button type="submit" name="disable_this" class="btn btn-primary">Submit</button>


    // Rule
    {
        "field": "disable_this",
            "action": "disable",
            "rules": {
                "name": "disable_parent",
                "operator": "isnot",
                "value": "yes"
        }
    }
